# Generated by Django 5.2.6 on 2025-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='resumen',
            field=models.CharField(blank=True, help_text='Descripción breve (máx. 160 chars)', max_length=160),
        ),
    ]
